- name: Install docker
  become: true
  community.general.pacman:
    name:
      - docker
      - docker-compose

- name: Ensure docker service is enabled
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Add current user to the docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true
