- name: Install neovim 0.10.4 (This is nasty workaround until lvim support 0.11.x)
  become: true
  ansible.builtin.pacman:
    name:
      - https://archive.archlinux.org/packages/n/neovim/neovim-0.10.4-2-x86_64.pkg.tar.zst

- name: Freeze neovim package
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#IgnorePkg'
    line: 'IgnorePkg = neovim'

- name: Install optional packages
  become: true
  ansible.builtin.pacman:
    name:
      - ripgrep
      - lazygit
      - fzf

- name: Install Nerd Fonts
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/DroidSansMono/DroidSansMNerdFont-Regular.otf
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/DroidSansMNerdFont-Regular.otf"
  notify: Update font-cache
