- name: Install Packages
  become: true
  ansible.builtin.dnf:
    name:
      - kitty
      - rofi
      - zsh
      - navi
      - openssl-devel
      - tk-devel
      - readline-devel
      - sqlite-devel
      - libpq-devel
      - neofetch
      - htop
      - flameshot
      - wireguard-tools
    update_cache: true

- name: Install pyenv
  ansible.builtin.shell:
    cmd: curl https://pyenv.run | bash
    creates: "{{ ansible_env.HOME }}/.pyenv"

- name: Install dnf-plugins-core
  become: true
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core

- name: Install docker repository
  become: true
  ansible.builtin.shell:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Install docker
  become: true
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Start docker servie
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: adding existing user '{{ user }}' to group sudo
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
