- name: Install awesome-git
  ansible.builtin.shell: paru -S awesome-git --noconfirm
  args:
    creates: /usr/bin/awesome

- name: Install essential packages
  become: true
  community.general.pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter

- name: Enable lightdm service
  become: true
  ansible.builtin.service:
    name: lightdm.service
    enabled: true
